# This file was generated by the {rix} R package v0.12.4 on 2024-10-03
# with following call:
# >rix(r_ver = "75b209227dff3cbfac19f510a62f9446c92beac4",
#  > r_pkgs = c("shiny",
#  > "shinytest2",
#  > "shinyvalidate",
#  > "rstudioapi",
#  > "usethis"),
#  > system_pkgs = c("chromium",
#  > "vscodium"),
#  > git_pkgs = NULL,
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses nixpkgs' revision 75b209227dff3cbfac19f510a62f9446c92beac4 for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/75b209227dff3cbfac19f510a62f9446c92beac4.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      languageserver
      rstudioapi
      shiny
      shinytest2
      shinyvalidate
      usethis;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      chromium
      glibcLocales
      nix
      R
      vscodium;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}
