# This file was generated by the {rix} R package v0.12.4 on 2024-10-03
# with following call:
# >rix(r_ver = "fd698a4ab779fb7fb95425f1b56974ba9c2fa16c",
#  > r_pkgs = c("shiny",
#  > "shinytest2"),
#  > system_pkgs = c("google-chrome",
#  > "vscodium"),
#  > git_pkgs = NULL,
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses nixpkgs' revision fd698a4ab779fb7fb95425f1b56974ba9c2fa16c for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/fd698a4ab779fb7fb95425f1b56974ba9c2fa16c.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      languageserver
      shiny
      shinytest2
      shinyvalidate
      rstudioapi;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      google-chrome
      nix
      R
      vscodium;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}
