name: check-app

on:
  push:
    branches:
      - main
      - master

jobs:
  test-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Build development environment
        run: |
          nix-build

      - name: Test app with nix
        id: test-app-nix
        run: |
          nix-shell default.nix --run "Rscript -e 'shinytest2::test_app()'"
      